implemented integration test for UpdateClient calls
icon-project/IBC-Integration pull request #298
Opened 2023-04-18 13:39 UTC by rupeshkarna

## Description:
Added integration test for UpdateClient method in icon light client

### Commit Message

```bash
implemented integration test for UpdateClient calls
```

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2023-04-19 06:47 UTC, ibrizsabin requested changes
Plz fix the commit msg in PR

2023-04-19 08:06 UTC, rupeshkarna commented
> Plz fix the commit msg in PR

It has been fixed

2023-04-19 10:51 UTC, sabinchitrakar approved these changes

2023-04-19 10:51 UTC, sabinchitrakar submitted a review, later dismissed

2023-04-19 10:52 UTC, ibrizsabin submitted a review, later dismissed

2023-04-28 14:37 UTC, ibrizsabin approved these changes

2023-04-28 14:37 UTC, merged