feat: implement entry point and fee logic
icon-project/IBC-Integration pull request #329
Opened 2023-04-27 06:57 UTC by shreyasbhat0

## Description:

### Commit Message

```bash
feat: implement entry point and fee logic
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [x] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2023-04-27 09:45 UTC, ibrizsabin commented on contracts/cosmwasm-vm/cw-ibc-core/src/msg.rs
> +
@shreyasbhat0  will we fix this on this PR ?

2023-04-27 09:48 UTC, ibrizsabin commented on contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/types.rs
> +
i think we can move this to common or use one from common.

2023-04-27 09:49 UTC, ibrizsabin commented on contracts/cosmwasm-vm/cw-ibc-core/src/ics02_client/types.rs
> +
we have this definition as well.

2023-04-27 09:52 UTC, ibrizsabin commented on contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
> +
lets map it to contract error. Due to poor debuggability of contracts its better to have more verbose error handling.

2023-04-27 09:54 UTC, ibrizsabin commented on contracts/cosmwasm-vm/cw-ibc-core/src/contract.rs
> +                    .unwrap();
looks like it already throws contract error so lets propagate via  "?;" to indicate that the error is compatible.

2023-04-27 10:04 UTC, ibrizsabin requested changes
most changes are refactoring so looks good to go with few changes if required

2023-04-27 10:06 UTC, shreyasbhat0 commented on contracts/cosmwasm-vm/cw-icon-light-client/src/bin/schema.rs
>          query: QueryMsg,
this because as i moved execute message to common and removed json schema which is not supported fro certain types .

2023-04-28 03:57 UTC, ibrizsabin approved these changes

2023-04-28 04:00 UTC, merged