feat: support expanding config value, convert json to yaml
icon-project/IBC-Integration pull request #398
Opened 2023-05-29 12:09 UTC by debendraoli

## Description:

This change allows expanding config values with OS Environment variables eliminating hard coded values on config file.

### Commit Message

```bash
feat: support expanding config value, convert json to yaml
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

N/A.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the unit tests
- [x] I only have one commit (if not, squash them into one commit).
- [x] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2023-05-29 13:01 UTC, AntonAndell requested changes

2023-05-29 13:01 UTC, AntonAndell commented on test/e2e/config.yaml
> +      repository: debendraoli/relayer
This should be the goloop image for now, relay should be a separate config or hard coded in the tests

2023-05-29 13:51 UTC, debendraoli commented on test/e2e/icon-icon_test.go
> +	optionDocker := relayer.CustomDockerImage(cfg.Counterparty.ChainConfig.Images.Repository, cfg.Counterparty.ChainConfig.Images.Version, "100:1000")
Sure. Wouldn't it is better taking values from config rather hard coded value?

2023-05-29 15:07 UTC, AntonAndell commented on test/e2e/icon-icon_test.go
> +	optionDocker := relayer.CustomDockerImage(cfg.Counterparty.ChainConfig.Images.Repository, cfg.Counterparty.ChainConfig.Images.Version, "100:1000")
Yeah taking from config would be fine but will be the same for all tests so a constant somewhere would also be okey

2023-05-30 10:09 UTC, redlarva commented on test/e2e/icon-icon_test.go
> +	optionDocker := relayer.CustomDockerImage(cfg.Counterparty.ChainConfig.Images.Repository, cfg.Counterparty.ChainConfig.Images.Version, "100:1000")
Yeah I agree with @AntonAndell ,We can use constant as we will be using same/latest version of relayer most of the time.I will revert this to use constant for relayer

2023-05-30 10:30 UTC, debendraoli commented on test/e2e/icon-icon_test.go
> +	optionDocker := relayer.CustomDockerImage(cfg.Counterparty.ChainConfig.Images.Repository, cfg.Counterparty.ChainConfig.Images.Version, "100:1000")
I have made use of constant and also overriding option when required from env.

2023-05-31 08:23 UTC, AntonAndell reviewed
Looks good just one question

2023-05-31 08:23 UTC, AntonAndell commented on test/e2e/config.yaml
> +      repository: iconloop/icon2-node
What is this docker? and why is it not the same as the other ICON chain?

2023-05-31 12:21 UTC, AntonAndell approved these changes

2023-06-01 05:17 UTC, redlarva approved these changes
looks good

2023-06-01 05:17 UTC, merged