feat: finalize xcall multi
icon-project/IBC-Integration pull request #457
Opened 2023-06-29 14:12 UTC by ibrizsabin

## Description:

### Commit Message

```bash
feat: finalize xcall multi
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2023-06-30 06:03 UTC, AntonAndell requested changes

2023-06-30 06:03 UTC, AntonAndell commented on contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
>              ACK_FAILURE_ID => self.reply_ack_on_error(msg),
Do we need to wait for any of these in cosmwasm?

2023-06-30 06:26 UTC, AntonAndell commented on contracts/cosmwasm-vm/cw-xcall-app/src/send_call_message.rs
>                  need_response,
Should be default false

2023-06-30 06:40 UTC, AntonAndell commented on contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/send_message.rs
> +        self.ensure_data_length(message.len())?;
```suggestion
```

2023-06-30 06:51 UTC, AntonAndell commented on contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/receive_packet.rs
> +    }
Return empty Ack here

2023-06-30 06:55 UTC, AntonAndell commented on contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/fee.rs
> +        let fees = self.get_unclaimed_packet_fee(deps.as_ref().storage, &nid, &address)?;
```suggestion
        let fees = self.get_unclaimed_packet_fee(deps.as_ref().storage, &nid, &<Caller>)?;
```

2023-06-30 07:04 UTC, AntonAndell commented on contracts/cosmwasm-vm/cw-common/src/xcall_app_msg.rs
> +    HandleCallMessage {
```suggestion
    HandleMessage {
```

2023-06-30 08:34 UTC, ibrizsabin commented on contracts/cosmwasm-vm/cw-common/src/xcall_connection_msg.rs
> +        net_to: NetworkAddress,
i guess its enogh only to have netId here since connection can just lookup config from nid and the actual recepient is already in message.

2023-07-06 07:14 UTC, AntonAndell commented on contracts/cosmwasm-vm/cw-xcall-app/src/contract.rs
>              ExecuteMsg::RemoveAdmin {} => self.remove_admin(deps.storage, info),
Remove both Update and remove. Set sets one admin and overwrites the old one

2023-07-06 07:16 UTC, AntonAndell commented on contracts/cosmwasm-vm/cw-xcall-app/src/contract.rs
>      pub fn validate_send_call(
Remove function

2023-07-06 07:17 UTC, AntonAndell commented on contracts/cosmwasm-vm/cw-xcall-app/src/send_call_message.rs
>          let message: CallServiceMessage = call_request.into();
Not resolved

2023-07-06 07:19 UTC, AntonAndell commented on contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs
> +            }
Remove setIBCConfig and and update/remove admin

2023-07-06 07:50 UTC, AntonAndell commented
https://github.com/icon-project/IBC-Integration/blob/b8d0f708cab93b3f462ef1b7b65a0bcef55b7137/contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/contract.rs#L102

Remove and ensure xcall handler

2023-07-06 07:53 UTC, AntonAndell commented
Fix order
https://github.com/icon-project/IBC-Integration/blob/b8d0f708cab93b3f462ef1b7b65a0bcef55b7137/contracts/cosmwasm-vm/cw-xcall-ibc-connection/src/xcall.rs#L18-L21

2023-07-06 07:55 UTC, AntonAndell commented
Remove
https://github.com/icon-project/IBC-Integration/blob/b8d0f708cab93b3f462ef1b7b65a0bcef55b7137/contracts/cosmwasm-vm/cw-xcall-multi/src/execute_call.rs#L53C18-L53C18

and add here:
https://github.com/icon-project/IBC-Integration/blob/b8d0f708cab93b3f462ef1b7b65a0bcef55b7137/contracts/cosmwasm-vm/cw-xcall-multi/src/execute_call.rs#L70-L71

2023-07-06 13:11 UTC, AntonAndell submitted a review, later dismissed
Looks good.
Ready to enter testing

2023-07-07 05:29 UTC, redlarva approved these changes
looks good to me

2023-07-07 05:32 UTC, merged