fix: archway channel event
icon-project/IBC-Integration pull request #458
Opened 2023-06-30 05:50 UTC by izyak

## Description:

### Commit Message

```bash
fix: archway eventlogs for channels
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2023-06-30 08:40 UTC, ibrizsabin commented on contracts/cosmwasm-vm/cw-ibc-core/src/ics04_channel/packet/acknowledgement.rs
> +                            .to_string();
unwrapping timeout caused issues last time when we worked on packet timeout and we had come up with this solution:
```   let timeout_height= packet.timeout.block().and_then(|b|{
                        Some(b.height.to_string())
                    }).unwrap_or("0".to_string());```

2023-06-30 08:47 UTC, ibrizsabin requested changes
i have a suggestion if in case the unwrap panics.

2023-07-03 13:41 UTC, sabinchitrakar approved these changes

2023-07-03 13:41 UTC, ibrizsabin approved these changes

2023-07-04 06:50 UTC, merged