466 initiate btp node for archway on icon testnet
icon-project/IBC-Integration pull request #480
Opened 2023-07-10 03:26 UTC by DeepakBomjan

## Description:

### Commit Message

```bash
type: commit message
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2023-07-10 03:29 UTC, DeepakBomjan commented
Hi @AntonAndell @redlarva @nightowl121 , I have added the workflow to deploy javascore contracts on Berlin testnet, I have updated the score address in gradle.properties file. The contracts which failed to deploy have been commented for now. Please have a look on failed contracts.

2023-07-10 05:05 UTC, AntonAndell requested changes
Can you also add a section to the readme. Like this: 
https://github.com/iconloop/btp2-testnet/blob/master/README.md

2023-07-10 05:05 UTC, AntonAndell commented on contracts/javascore/gradle.properties
> +# berlin.contracts.mock-dapp=cx6a52b5f7e24c2bcea7758341dcb599f18dd03ecb
Can be removed, since contract wont be used

2023-07-10 05:05 UTC, AntonAndell commented on contracts/javascore/gradle.properties
> +berlin.contracts.xcall=cx5a043c58a278cd84fea67d36d4f45b44775eeaf3
Can be removed, since contract wont be used

2023-08-14 04:59 UTC, DeepakBomjan commented
Opening new PR as the current PR carries an irrelevant changes also

2023-08-14 05:32 UTC, closed without merging