fix: port initialization removed
icon-project/IBC-Integration pull request #657
Opened 2023-08-23 13:59 UTC by qwerty0789

## Description:

### Commit Message

```bash
type: commit message
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [x] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2023-08-23 14:49 UTC, AntonAndell requested changes
Looks good, but the _port parameter change also has to be reflected in the deployment in the gradle

2023-08-24 06:12 UTC, AntonAndell requested changes
Also, forgot but have you tried the e2e, Might be that the parameter needs to be changed there aswell

2023-08-29 11:00 UTC, redlarva approved these changes
looks good and all e2e test pass

2023-08-29 11:07 UTC, AntonAndell approved these changes

2023-08-29 11:07 UTC, merged