fix: hasPacketRecieve method removed
icon-project/IBC-Integration pull request #664
Opened 2023-08-25 09:15 UTC by qwerty0789

## Description:

### Commit Message

```bash
type: commit message
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2023-08-25 10:46 UTC, AntonAndell commented
@izyak @viveksharmapoudel  Which one does the relay use?

2023-08-28 04:34 UTC, izyak approved these changes

2023-08-28 04:34 UTC, izyak commented
It used getPacketReceipt method

2023-08-28 05:22 UTC, redlarva requested changes
We should update the `getPacketReceipt` method. Currently, if the `portId` or `channelId` doesn't exist, it throws an error. I suggest changing this behavior to have it return false when `portId` or `channelId`  does not exists. This issue also extends to the CosmWasm ibc contract, where currently an error occurs if a packet is not found.

2023-08-31 04:28 UTC, redlarva commented
Additionally ,in our e2e/integration tests, we currently use the hasPacketReceipt method to confirm if packets reached the target chain for both Icon and CosmWasm contracts. Instead of hasPacketReceipt, let's use the getPacketReceipt method for validation in e2e/integration setup.

2023-09-04 08:04 UTC, redlarva commented on contracts/javascore/ibc/src/main/java/ibc/ics24/host/IBCStore.java
> +        }
```suggestion
           return packetReceipts.at(portId).at(channelId).getOrDefault(sequence, false);
```
should works fine

2023-09-06 03:43 UTC, redlarva approved these changes
looks good

2023-09-06 03:43 UTC, merged