Feat/e2e demo script
icon-project/IBC-Integration pull request #667
Opened 2023-08-27 01:09 UTC by redlarva

## Description:

### Commit Message

```bash
feat(test) : e2e demo setup
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2023-08-28 10:27 UTC, AntonAndell requested changes
Just a veri minor comment

2023-08-28 10:27 UTC, AntonAndell commented on test/chains/icon/localnet.go
> +	_, _ = c.executeContract(ctx, "cx0000000000000000000000000000000000000000", interchaintest.IBCOwnerAccoun, "registerPRep", params)
IBCOwnerAccoun -> IBCOwnerAccount

2023-08-29 04:16 UTC, ibrizsabin approved these changes

2023-08-29 04:27 UTC, redlarva commented on test/chains/icon/localnet.go
> +	_, _ = c.executeContract(ctx, "cx0000000000000000000000000000000000000000", interchaintest.IBCOwnerAccoun, "registerPRep", params)
fixed

2023-08-29 04:59 UTC, AntonAndell approved these changes
Looks good

2023-08-29 06:58 UTC, ibrizsabin approved these changes

2023-08-29 06:59 UTC, merged